### ISSUE TITLE
ValueError: AlfWorld Environment [expert_plan, expert_type] 

### ISSUE THREAD

**Issue by ai-nikolai** [noahshinn/reflexion#31]
```shell
    -----
    Starting run with the following parameters:
    Run name: reflexion_run_logs
    Number of trials: 1
    Number of environments: 1
    Use memory: True

    Sending all logs to `reflexion_run_logs`
    -----
    
Initializing AlfredTWEnv...
Checking for solvable games...
Overall we have 134 games
Evaluating with 134 games
Traceback (most recent call last):
  File "/reflexion/alfworld_runs/main.py", line 119, in <module>
    main(args)
  File "/reflexion/alfworld_runs/main.py", line 100, in main
    run_trial(trial_log_path, world_log_path, trial_idx, env_configs, args.use_memory, args.model)
  File "/reflexion/alfworld_runs/alfworld_trial.py", line 99, in run_trial
    env = env.init_env(batch_size=1)
  File "/reflexion/env_alfworld/lib/python3.9/site-packages/alfworld/agents/environment/alfred_tw_env.py", line 224, in init_env
    infos = textworld.EnvInfos(won=True, admissible_commands=True, expert_type=expert_type, expert_plan=expert_plan, extras=["gamefile"])
  File "/reflexion/env_alfworld/lib/python3.9/site-packages/textworld/core.py", line 109, in __init__
    raise ValueError(msg)
ValueError: Unknown information requested: ['expert_plan', 'expert_type']. Available information are: ['admissible_commands', 'command_templates', 'description', 'entities', 'extras', 'facts', 'fail_facts', 'feedback', 'game', 'intermediate_reward', 'inventory', 'last_action', 'last_command', 'location', 'lost', 'max_score', 'moves', 'objective', 'policy_commands', 'score', 'verbs', 'win_facts', 'won']
```

**Comment by ai-nikolai** [comment]
@noahshinn thanks for closing the issue.  What resolved the issue?
